### ISSUE TITLE
discord_modify_channel rtc_region issue

### ISSUE THREAD

**Issue by false** [Cogmasters/concord#138]
Hello,

Using discord_modify_channel results in the following error :
`[31mERROR[0m [90mdiscord-rest_request.c:391:[0m [DISCORD_REQUEST] {"code": 50035, "errors": {"rtc_region": {"_errors": [{"code": "BASE_TYPE_CHOICES", "message": "Value must be one of ('brazil', 'hongkong', 'india', 'japan', 'rotterdam', 'russia', 'singapore', 'south-korea', 'southafrica', 'sydney', 'us-central', 'us-east', 'us-south', 'us-west')."}]}}, "message": "Invalid Form Body"}`

It happens when I want to rename a discord channel. The channel doesn't get renamed, the request fails.

It doesn't work on the the version 2.1.0, 2.2.0, and the current master branch.

Do you observe the same issue ?

Thanks,

**Comment by ThePedroo** [comment]
Could you show your http log without setting a region?

**Comment by lcsmuller** [comment]
Closed due to inactivity
