### ISSUE TITLE
Raspberry Pi (64-bit) library setup problem

### ISSUE THREAD

**Issue by Macintosh-Fan** [Cogmasters/concord#149]
## Describe the bug
Something with the installation went wrong.

## Screenshots
<img width="578" alt="image" src="https://github.com/Cogmasters/concord/assets/50642934/b3b05a2e-a81b-4c5b-a170-029e896904de">

## To Reproduce
Commands run on Raspberry Pi (64-bit):
`apt update && apt install -y libcurl4-openssl-dev`
`git clone https://github.com/cogmasters/concord.git && cd concord`
`make`
`gcc myBot.c -o myBot -pthread -ldiscord -lcurl` (either in `concord` or just outside of `concord`, still does not work)

## Version
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Comment by HackerSmacker** [comment]
Did you ever run `make install`?

**Comment by Macintosh-Fan** [comment]
> Did you ever run `make install`?

Didn't know I had to do that. Thanks, @HackerSmacker! Compiling works just fine now.

**Comment by HackerSmacker** [comment]
Awesome, good luck and have fun!
