### ISSUE TITLE
Wrong compiler for discord_codecs breaks cross

### ISSUE THREAD

**Issue by OPNA2608** [Cogmasters/concord#152]
## Describe the bug
https://github.com/Cogmasters/concord/blob/769bdb74b066b2f250a3ec9199063532e4dcccf2/gencodecs/Makefile#L68-L69

The `OUT_O` produced here gets linked with the rest of the code that's built with the cross-compiling `CC` for the target platform, but this currently uses the same `CC` that's used in the rest of `gencodecs` to target the host platform. Attempting to cross-compile to a different platform will thus abort at the linking step, when the linker rejects the object in the wrong format.

```
aarch64-unknown-linux-gnu-gcc -shared -lcurl -o ../lib/libdiscord.so concord-once.o discord-refcount.o discord-rest.o discord-rest_request.o discord-rest_ratelimit.o discord-client.o discord-events.o discord-cache.o discord-loop.o discord-gateway.o discord-gateway_dispatch.o discord-messagecommands.o discord-timer.o discord-misc.o discord-worker.o application_command.o auto_moderation.o interaction.o audit_log.o channel.o emoji.o gateway.o guild.o guild_scheduled_event.o guild_template.o invite.o oauth2.o user.o voice.o webhook.o ../gencodecs/discord_codecs.o ../core/cog-utils.o ../core/io_poller.o ../core/user-agent.o ../core/websockets.o ../core/curl-websocket.o ../core/jsmn-find.o ../core/json-build.o ../core/log.o ../core/logconf.o ../core/priority_queue.o ../core/anomap.o ../core/sha1.o ../core/threadpool.o ../core/queriec.o
/nix/store/lvr57hbrpjvg7jyh0j2a1bx2cvwypjqh-aarch64-unknown-linux-gnu-binutils-2.40/bin/aarch64-unknown-linux-gnu-ld: ../gencodecs/discord_codecs.o: Relocations in generic ELF (EM: 62)
/nix/store/lvr57hbrpjvg7jyh0j2a1bx2cvwypjqh-aarch64-unknown-linux-gnu-binutils-2.40/bin/aarch64-unknown-linux-gnu-ld: ../gencodecs/discord_codecs.o: Relocations in generic ELF (EM: 62)
/nix/store/lvr57hbrpjvg7jyh0j2a1bx2cvwypjqh-aarch64-unknown-linux-gnu-binutils-2.40/bin/aarch64-unknown-linux-gnu-ld: ../gencodecs/discord_codecs.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

```
/tmp/nix-build-concord-aarch64-unknown-linux-gnu-2.2.1.drv-0/source/src/discord-refcount.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), with debug_info, not stripped
/tmp/nix-build-concord-aarch64-unknown-linux-gnu-2.2.1.drv-0/source/gencodecs/discord_codecs.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```

## Expected behavior
1. `gencodecs/Makefile` uses separate `HOST_CC` & `HOST_CPP` variables (or whatever standard name they might have, if any) for the host-platform-targeting things, and inherits the target-platform-targeting `CC` from the main `Makefile`
2. All but the linked-above line use `HOST_CC` / `HOST_CPP` to target the host platform, while the linked line uses `CC` to cross-compile for the target platform

## Screenshots
n/a

## To Reproduce
Use a cross-compiling `CC` for a target where objects for the host & target platform cannot be mixed (i.e. x86_64 and aarch64, not glibc x86_64 and musl x86_64)

## Version
Concord 2.2.1
Linux, 64-bit
```
Distributor ID:	NixOS
Description:	NixOS 23.05 (Stoat)
Release:	23.05
Codename:	stoat
```

**Comment by HackerSmacker** [comment]
The current procedure is to enter the gencodecs directory and invoke `make` with `$(CC)` overriden on the command line or in the Makefile, however, this does NOT properly cross-compile. Let me fix that and make a few notes on that!

**Comment by HackerSmacker** [comment]
Okay, it should be fixed. I made a note in the README that explains how to do it -- I tried to make it as simple as possible. Feel free to drop another comment if you've got any more feedback, and thanks for the report!

**Comment by OPNA2608** [comment]
Hmm, well cross-compiling works perfectly well for me if I patch that Makefile to use a non-`CC` variable and inherit `CC` from the main Makefile that calls into it instead. I feel like having a separate step for gencodecs is just pointless complexity.

**Comment by HackerSmacker** [comment]
Well, to be fair, there is a reason the architecture is the way it is -- gencodecs is not a component that is exclusive to Concord, and was designed to be somewhat generic. Regardless, the change has been made and it should be pretty easy for 99.99% of users to roll with.

**Comment by OPNA2608** [comment]
> gencodecs […] was designed to be somewhat generic

I think that's even more of an argument in favour of not needlessly overriding these implicit Make variables then, or changing *something* about the way these are assigned at least. With GNU Make, `CC` and `CPP` are already implicitly defined and have reasonably-likely fallback values. The file already uses conditional variable assignment for `CFLAGS`, so the same could be done for those two if you really want to be sure that it has *some* assignment.

But yes, feel free to close as the original issue has been resolved. Just trying to cut down the patching I need to do so everything behaves as it should.
