### ISSUE TITLE
Ship a pkg-config file

### ISSUE THREAD

**Issue by v1993** [Cogmasters/concord#160]
## Describe the feature
Shipping a simple pkg-config file would make adding this library to CMake- or Meson-based projects more straightforward.

## Version
Any, to my knowledge.

## Additional context
This is what file would probably look like when installed:

```pkg
prefix=/usr
libdir=${prefix}/lib
includedir=${prefix}/include

Name: Concord
Description: A Discord API wrapper library made in C
URL: https://cogmasters.github.io/concord/
Version: 2.2.1
Libs: -L${libdir} -ldiscord
Requires.private: libcurl
Cflags: -I${includedir}
```

The first line should be set to prefix used for installation. Probably just `echo`ing into file directly from Makefile (and then calling `install` on it) is sufficient in this case.

**Comment by lcsmuller** [comment]
Closed by #183
