### ISSUE TITLE
`DISCORD_MAX_MESSAGE_LEN` has the wrong value

### ISSUE THREAD

**Issue by LyricLy** [Cogmasters/concord#166]
The largest possible message length is 4,000, not 2,000.

**Comment by Ratakor** [comment]
No, 4000 is for nitro users.

**Comment by ThePedroo** [comment]
That buffer (size) is meant to be used by the bot for sending messages, not for receiving. Do you mean for receiving?

**Comment by LyricLy** [comment]
Oh, it's for buffers to format text into.
