### ISSUE TITLE
Pass additional data to callbacks

### ISSUE THREAD

**Issue by SoujiThenria** [Cogmasters/concord#177]
## Describe the feature
Pass additional data (e.g. database handle) to callbacks triggered on events.

For example, for `discord_set_on_interaction_create` and alike, it would be nice to be able to pass additional data without using a global variable, but using something like this:
```
void discord_set_on_interaction_create(struct discord *client, void (*callback)(struct discord *, const struct discord_interaction *), void *data)
```

## Version
concord version: 769bdb74b066b2f250a3ec9199063532e4dcccf2

LSB Version:    1.0
Distributor ID: VoidLinux
Description:    Void Linux
Release:        rolling
Codename:       void

**Comment by ThePedroo** [comment]
Maybe what you are looking is [discord_set_data](https://cogmasters.github.io/concord/group__DiscordClient.html#gab4be84906e3794c24a69b781b2271656)? This allows to set a variable that is accessible from anywhere where you have access to Concord client
