### ISSUE TITLE
<struct discord_message>.timestamp is not being set

### ISSUE THREAD

**Issue by scinscinscin** [Cogmasters/concord#46]
**Describe the bug**
Describe what you see that (you think) is wrong.

The library is not setting the timestamp member in discord_message struct instances.

**Expected behavior**

I expect the member to be set to the timestamp of when the message was sent

**Screenshots**
![image](https://user-images.githubusercontent.com/65155829/158254071-4ab2193d-73c6-46b4-bedb-63e95cbf3bc6.png)
![image](https://user-images.githubusercontent.com/65155829/158254100-ad226d1e-bbf8-4fe2-8f6c-ae65a8b074a5.png)

**To Reproduce**
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "concord/discord.h"

void on_message_create(struct discord *client, const struct discord_message *msg)
{
	if (msg->author->bot)
		return;

	printf("A message was created at: %lu\n", msg->timestamp);
}

int main(int argc, char *argv[])
{
	const char *config_file;
	if (argc > 1)
		config_file = argv[1];
	else
		config_file = "./config.json";

	ccord_global_init();
	struct discord *client = discord_config_init(config_file);
	assert(NULL != client && "Couldn't initialize client");

	discord_set_on_message_create(client, &on_message_create);
	discord_run(client);

	discord_cleanup(client);
	ccord_global_cleanup();
}
```

**Version**
I installed the library from source yesterday, but I deleted the cloned repo so I can't give the top hash

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

**Comment by lcsmuller** [comment]
Can confirm there seems to be a regression after introducing #27 (more specifically the gencodecs portion of it), thank you for the thorough explanation!
