### ISSUE TITLE
Cannot build on MacOS

### ISSUE THREAD

**Issue by Frityet** [Cogmasters/concord#71]
**Describe the bug**
I cannot build on MacOS monterey

**Expected behavior**
a built binary

**Screenshots**
<img width="483" alt="Screen Shot 2022-06-15 at 17 06 11" src="https://user-images.githubusercontent.com/25426233/173962113-96a45d7a-7735-4303-abcb-606712955839.png">

**To Reproduce**
type `make` in the repo in MacOS montery

**Version**
v2.0.0, MacOS montery: `Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64`

**Comment by HackerSmacker** [comment]
To all those reading in the future:
```
cd gencodecs
make clean
make
cd ..
make
```

The precooked gencodecs material will be removed right this second.
